/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSongDialog: typeof import('./components/AddSongDialog.vue')['default']
    AddTagDialog: typeof import('./components/AddTagDialog.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    PlayList: typeof import('./components/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsAudio: typeof import('./components/settings/SettingsAudio.vue')['default']
    SettingsBluetooth: typeof import('./components/settings/SettingsBluetooth.vue')['default']
    SettingsDevice: typeof import('./components/settings/SettingsDevice.vue')['default']
    SettingsMenu: typeof import('./components/settings/SettingsMenu.vue')['default']
    SettingsNetwork: typeof import('./components/settings/SettingsNetwork.vue')['default']
    SettingsTags: typeof import('./components/settings/SettingsTags.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
  }
}
