/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSongDialog: typeof import('./components/AddSongDialog.vue')['default']
    MusicPlayer: typeof import('./components/MusicPlayer.vue')['default']
    PlayList: typeof import('./components/PlayList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./components/Settings.vue')['default']
    Tags: typeof import('./components/Tags.vue')['default']
    TopMenu: typeof import('./components/TopMenu.vue')['default']
  }
}
